name: coinbase_wallet_sdk
description: Fluter implementation of Coinbase Wallet SDK.
version: 1.0.7
homepage: https://wallet.coinbase.com

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.coinbase.flutter.wallet_sdk
        pluginClass: CoinbaseWalletSdkFlutterPlugin
      ios:
        pluginClass: CoinbaseWalletSdkFlutterPlugin
