platform :ios, '13.0'
use_frameworks!

target 'SampleClient' do
  pod 'CoinbaseWalletSDK', path: '../../', :testspecs => ['Test']
end

target 'SampleWallet' do
  pod 'CoinbaseWalletSDK/Host', path: '../../'
end
