name: iOS tagging [auto]

on:
  push:
    branches:
      - master
      - test-branch

jobs:
  authorize:
    name: Authorize
    runs-on: ubuntu-latest
    steps:
      - name: ${{ github.actor }} permission check to update release version
        uses: "lannonbr/repo-permission-check-action@2.0.2"
        with:
          permission: "write"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  autotag:
    name: Auto Tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ButlerLogic/action-autotag@1.1.1
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          strategy: regex
          root: "CoinbaseWalletSDK.podspec"
          regex_pattern: "s.version\\s*=\\s*'((\\d+)\\.(\\d+)\\.(\\d+))'"
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: autotag
    steps: 
      - run: echo ${{needs.job1.outputs}}