name: iOS tagging [auto]

on:
  push:
    branches:
      - master
      - test-branch

jobs:
  autotag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ButlerLogic/action-autotag@1.1.1
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          strategy: regex
          root: "CoinbaseWalletSDK.podspec"
          regex_pattern: "s.version\s*=\s*'((\d+)\.(\d+)\.(\d+))'"
