name: Run Tests

on:
  pull_request:
    branches:
      - master

jobs:
  android:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # config java sdk version
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      # Run Android unit tests
      - name: Run unit testing
        run: |
          cd android
          ./gradlew :walletsdk:testDebugUnitTest

  ios:
    name: iOS
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.5'
          bundler-cache: true

      - name: Run unit test
        run: bundle exec pod lib lint --verbose
