name: Run Tests

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # config java sdk version
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      # Run Android unit tests
      - name: Run unit testing
        run: |
          cd shoppingList/
          ./gradlew :walletsdk:testDebugUnitTest
