name: Version Update PR

on:
  workflow_dispatch:
    inputs:
      packageVersion:
        description: "The version to publish in MAJOR.MINOR.PATCH format"
        required: true
        default: ""

jobs:
  authorize:
    name: Authorize
    runs-on: ubuntu-latest
    steps:
      - name: ${{ github.actor }} permission check to update release version
        uses: "lannonbr/repo-permission-check-action@2.0.2"
        with:
          permission: "write"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  version:
    name: Update package version
    runs-on: macOS-latest
    needs: [authorize]
    env:
      PACKAGE_VERSION: ${{ github.event.inputs.packageVersion }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update iOS version
        run: |
          sed -i '' -E "s/= '[0-9]+\.[0-9]+\.[0-9]+/= '${{ env.PACKAGE_VERSION }}/" CoinbaseWalletSDK.podspec
          sed -i '' -E 's/= "[0-9]+\.[0-9]+\.[0-9]+/= "${{ env.PACKAGE_VERSION }}/' ios/CoinbaseWalletSDK/Resources/CoinbaseWalletSDK+version.swift
      
      - name: Update Android version
        run: |
          sed -i '' -E 's/(versionName) "[0-9]+\.[0-9]+\.[0-9]+/\1 "${{ env.PACKAGE_VERSION }}/' android/walletsdk/build.gradle
          sed -i '' -E 's/(versionName =) "[0-9]+\.[0-9]+\.[0-9]+/\1 "${{ env.PACKAGE_VERSION }}/' android/scripts/publish-root.gradle
          
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.5'
          bundler-cache: true

      - name: Update iOS example
        run: bundle exec pod install
        working-directory: ios/example

      - name: Open pull request
        uses: peter-evans/create-pull-request@v4
        with:
          add-paths: |
            CoinbaseWalletSDK.podspec
            ios/CoinbaseWalletSDK/Resources/CoinbaseWalletSDK+version.swift
            ios/example/Podfile.lock
            android/walletsdk/build.gradle
            android/scripts/publish-root.gradle
          title: "[Version update] v${{ env.PACKAGE_VERSION }}"
          body: "Automated workflow: version update"
          branch: version-update-v${{ env.PACKAGE_VERSION }}
          delete-branch: true
          commit-message: "[Version update] v${{ env.PACKAGE_VERSION }}"
          labels: version-update
