name: Version Update PR (Client)

on:
  workflow_dispatch:
    inputs:
      packageVersion:
        description: "The version to publish in MAJOR.MINOR.PATCH format"
        required: true
        default: ""

jobs:
  authorize:
    name: Authorize
    runs-on: ubuntu-latest
    steps:
      - name: ${{ github.actor }} permission check to update release version
        uses: "lannonbr/repo-permission-check-action@2.0.2"
        with:
          permission: "write"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  version:
    name: Update package version
    runs-on: macOS-latest
    needs: authorize
    env:
      V_REGEX: '[0-9]+\.[0-9]+\.[0-9]+'
      NEW_VERSION: ${{ github.event.inputs.packageVersion }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update iOS version
        run: |
          sed -i '' -E "s/= '${{env.V_REGEX}}/= '${{env.NEW_VERSION}}/" CoinbaseWalletSDK.podspec
          sed -i '' -E 's/= "${{env.V_REGEX}}/= "${{env.NEW_VERSION}}/' ios/CoinbaseWalletSDK/MobileWalletProtocol.swift

      - name: Update Android version
        run: |
          sed -i '' -E 's/(sdk-version =) "${{env.V_REGEX}}/\1 "${{env.NEW_VERSION}}/' android/gradle/libs.versions.toml

      - name: Update React Native version
        run: |
          sed -i '' -E "s/(CoinbaseWalletSDK\/CrossPlatform',) '${{env.V_REGEX}}/\1 '${{env.NEW_VERSION}}/" react-native/client/ios/CoinbaseWalletSDKExpo.podspec
          sed -i '' -E 's/(com.coinbase:coinbase-wallet-sdk):${{env.V_REGEX}}/\1:${{env.NEW_VERSION}}/' react-native/client/android/build.gradle
          sed -i '' -E 's/(version":) "${{env.V_REGEX}}/\1 "${{env.NEW_VERSION}}/' react-native/client/package.json

      - name: Update Flutter version
        run: |
          sed -i '' -E "s/(CoinbaseWalletSDK\/CrossPlatform',) '${{env.V_REGEX}}/\1 '${{env.NEW_VERSION}}/" flutter/ios/coinbase_wallet_sdk.podspec
          sed -i '' -E 's/(com.coinbase:coinbase-wallet-sdk):${{env.V_REGEX}}/\1:${{env.NEW_VERSION}}/' flutter/android/build.gradle
          sed -i '' -E 's/(version:) ${{env.V_REGEX}}/\1 ${{env.NEW_VERSION}}/' flutter/pubspec.yaml

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7.5"
          bundler-cache: true

      - name: Update iOS example
        run: bundle exec pod install
        working-directory: ios/example

      # - name: Update React Native example
      #   run: bundle exec pod install
      #   working-directory: react-native/example/ios

      # - name: Update Flutter example
      #   run: bundle exec pod install
      #   working-directory: flutter/example/ios

      - name: Open pull request
        uses: peter-evans/create-pull-request@v4
        with:
          add-paths: |
            CoinbaseWalletSDK.podspec
            ios/CoinbaseWalletSDK/MobileWalletProtocol.swift
            ios/example/Podfile.lock
            android/gradle/libs.versions.toml
            react-native/client/ios/CoinbaseWalletSDKExpo.podspec
            react-native/client/android/build.gradle
            react-native/client/package.json
            flutter/ios/coinbase_wallet_sdk.podspec
            flutter/android/build.gradle
            flutter/pubspec.yaml
          title: "[Version update] v${{env.NEW_VERSION}}"
          body: "Automated workflow: version update"
          branch: version-update-v${{env.NEW_VERSION}}
          reviewers: |
            bangtoven
            vishnumad
          commit-message: "[Version update] v${{env.NEW_VERSION}}"
          labels: version-update
          delete-branch: true
